// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9lyvGCn6xj2TCZyP1vcxYvqNrkAdF7A',
    appId: '1:645839321843:web:0f4655d5be35c9204d5586',
    messagingSenderId: '645839321843',
    projectId: 'chatmobile-118cc',
    authDomain: 'chatmobile-118cc.firebaseapp.com',
    databaseURL: 'https://chatmobile-118cc-default-rtdb.firebaseio.com',
    storageBucket: 'chatmobile-118cc.appspot.com',
    measurementId: 'G-X51PTNWS8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSr7n1BDX7O7AXp24R6wYztI1bY7ajkE',
    appId: '1:645839321843:android:bca6a5534b506d194d5586',
    messagingSenderId: '645839321843',
    projectId: 'chatmobile-118cc',
    databaseURL: 'https://chatmobile-118cc-default-rtdb.firebaseio.com',
    storageBucket: 'chatmobile-118cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1oEFZfF0XnuxjBf99LWjfVDeAjnGamDU',
    appId: '1:645839321843:ios:464d30129b0812a84d5586',
    messagingSenderId: '645839321843',
    projectId: 'chatmobile-118cc',
    databaseURL: 'https://chatmobile-118cc-default-rtdb.firebaseio.com',
    storageBucket: 'chatmobile-118cc.appspot.com',
    iosClientId: '645839321843-oquds5ulpgu0nfj3kq7m4ejodclnc6rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1oEFZfF0XnuxjBf99LWjfVDeAjnGamDU',
    appId: '1:645839321843:ios:464d30129b0812a84d5586',
    messagingSenderId: '645839321843',
    projectId: 'chatmobile-118cc',
    databaseURL: 'https://chatmobile-118cc-default-rtdb.firebaseio.com',
    storageBucket: 'chatmobile-118cc.appspot.com',
    iosClientId: '645839321843-oquds5ulpgu0nfj3kq7m4ejodclnc6rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMobile',
  );
}
